### ISSUE TITLE
runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by bert2002** [persistenceOne/persistenceCore#142]
Hi,
I am trying to run a node based on the instructions [here](https://github.com/persistenceOne/awesome-persistence/blob/main/Validator.md) and running into following erros:

```
$ persistenceCore start
7:01AM INF starting node with ABCI Tendermint in-process
7:01AM INF service start impl=multiAppConn module=proxy msg={}   
7:01AM INF service start connection=query impl=localClient module=abci-client msg={}
7:01AM INF service start connection=snapshot impl=localClient module=abci-client msg={}
7:01AM INF service start connection=mempool impl=localClient module=abci-client msg={}
7:01AM INF service start connection=consensus impl=localClient module=abci-client msg={}
7:01AM INF service start impl=EventBus module=events msg={}
7:01AM INF service start impl=PubSub module=pubsub msg={}
7:01AM INF service start impl=IndexerService module=txindex msg={}
7:01AM INF ABCI Handshake App Info hash="�\x7f9�QʼM\x17�\x7f�`\x0ec��\f\x7f}�)���}��ߚ\b." height=6393453 module=consensus protocol-version=0 software-version=v3.2.0
7:01AM INF ABCI Replay Blocks appHeight=6393453 module=consensus stateHeight=6393453 storeHeight=6393454
7:01AM INF Replay last block using real app module=consensus
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x16920cd]

goroutine 1 [running]:
github.com/cosmos/cosmos-sdk/x/upgrade.BeginBlocker({{0xc0010098c0, 0x22}, 0xc003185200, {0x253be20, 0xc0031b16d0}, {0x255cd60, 0xc001039a80}, 0xc0031eeb70, {0x2535da0, 0xc000c8bdc0}, ...}, ...)
        github.com/cosmos/cosmos-sdk@v0.45.9/x/upgrade/abci.go:38 +0x100d
github.com/cosmos/cosmos-sdk/x/upgrade.AppModule.BeginBlock(...)
        github.com/cosmos/cosmos-sdk@v0.45.9/x/upgrade/module.go:130
github.com/cosmos/cosmos-sdk/types/module.(*Manager).BeginBlock(_, {{0x254f1e0, 0xc000130000}, {0x255ea20, 0xc00c7c2900}, {{0xb, 0x0}, {0xc00c336e40, 0x6}, 0x618e6e, ...}, ...}, ...)
        github.com/cosmos/cosmos-sdk@v0.45.9/types/module/module.go:491 +0x3bb
github.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).BeginBlock(_, {{0xc00c79d020, 0x20, 0x20}, {{0xb, 0x0}, {0xc00c336e40, 0x6}, 0x618e6e, {0x2e933409, ...}, ...}, ...})
        github.com/cosmos/cosmos-sdk@v0.45.9/baseapp/abci.go:177 +0x97b
github.com/tendermint/tendermint/abci/client.(*localClient).BeginBlockSync(_, {{0xc00c79d020, 0x20, 0x20}, {{0xb, 0x0}, {0xc00c336e40, 0x6}, 0x618e6e, {0x2e933409, ...}, ...}, ...})
        github.com/tendermint/tendermint@v0.34.21/abci/client/local_client.go:280 +0x118
github.com/tendermint/tendermint/proxy.(*appConnConsensus).BeginBlockSync(_, {{0xc00c79d020, 0x20, 0x20}, {{0xb, 0x0}, {0xc00c336e40, 0x6}, 0x618e6e, {0x2e933409, ...}, ...}, ...})
        github.com/tendermint/tendermint@v0.34.21/proxy/app_conn.go:81 +0x55
github.com/tendermint/tendermint/state.execBlockOnProxyApp({0x25502b8?, 0xc00106d440}, {0x25570c0, 0xc008a80e10}, 0xc0000f6d20, {0x255df90, 0xc008dfe3c0}, 0x618e6d?)
        github.com/tendermint/tendermint@v0.34.21/state/execution.go:307 +0x3dd
github.com/tendermint/tendermint/state.(*BlockExecutor).ApplyBlock(_, {{{0xb, 0x0}, {0xc008a597c8, 0x8}}, {0xc008a597e0, 0x6}, 0x1, 0x618e6d, {{0xc00776e0e0, ...}, ...}, ...}, ...)
        github.com/tendermint/tendermint@v0.34.21/state/execution.go:140 +0x171
github.com/tendermint/tendermint/consensus.(*Handshaker).replayBlock(_, {{{0xb, 0x0}, {0xc008a597c8, 0x8}}, {0xc008a597e0, 0x6}, 0x1, 0x618e6d, {{0xc00776e0e0, ...}, ...}, ...}, ...)
        github.com/tendermint/tendermint@v0.34.21/consensus/replay.go:503 +0x23c
github.com/tendermint/tendermint/consensus.(*Handshaker).ReplayBlocks(_, {{{0xb, 0x0}, {0xc008a597c8, 0x8}}, {0xc008a597e0, 0x6}, 0x1, 0x618e6d, {{0xc00776e0e0, ...}, ...}, ...}, ...)
        github.com/tendermint/tendermint@v0.34.21/consensus/replay.go:416 +0x7ae
github.com/tendermint/tendermint/consensus.(*Handshaker).Handshake(0xc01e8d1f78, {0x255f470, 0xc0010bf5f0})
        github.com/tendermint/tendermint@v0.34.21/consensus/replay.go:268 +0x3d4
github.com/tendermint/tendermint/node.doHandshake({_, _}, {{{0xb, 0x0}, {0xc008a597c8, 0x8}}, {0xc008a597e0, 0x6}, 0x1, 0x618e6d, ...}, ...)
        github.com/tendermint/tendermint@v0.34.21/node/node.go:330 +0x1b8
github.com/tendermint/tendermint/node.NewNode(0xc001081540, {0x254bda0, 0xc0000ca820}, 0xc0062fc3d0, {0x2536f20, 0xc006590b10}, 0x0?, 0x0?, 0xc0062fc630, {0x25502b8, ...}, ...)
        github.com/tendermint/tendermint@v0.34.21/node/node.go:778 +0x597
github.com/cosmos/cosmos-sdk/server.startInProcess(_, {{0x0, 0x0, 0x0}, {0x256ab18, 0xc00113de60}, {0x0, 0x0}, {0x2554a48, 0xc001039a80}, ...}, ...)
        github.com/cosmos/cosmos-sdk@v0.45.9/server/start.go:280 +0x7db
github.com/cosmos/cosmos-sdk/server.StartCmd.func2(0xc0010ab680?, {0x33acd40?, 0x0?, 0x0?})
        github.com/cosmos/cosmos-sdk@v0.45.9/server/start.go:128 +0x169
github.com/spf13/cobra.(*Command).execute(0xc0010ab680, {0x33acd40, 0x0, 0x0})
        github.com/spf13/cobra@v1.5.0/command.go:872 +0x694
github.com/spf13/cobra.(*Command).ExecuteC(0xc00107e280)
        github.com/spf13/cobra@v1.5.0/command.go:990 +0x3bd
github.com/spf13/cobra.(*Command).Execute(...)
        github.com/spf13/cobra@v1.5.0/command.go:918
github.com/spf13/cobra.(*Command).ExecuteContext(...)
        github.com/spf13/cobra@v1.5.0/command.go:911
github.com/cosmos/cosmos-sdk/server/cmd.Execute(0x0?, {0xc0010098c0, 0x22})
        github.com/cosmos/cosmos-sdk@v0.45.9/server/cmd/execute.go:36 +0x1eb
main.main()
        github.com/persistenceOne/persistenceCore/v3/cmd/persistenceCore/main.go:22 +0x2c
```

I build the binary from branch `v3.2.0` with golang `go1.19.2`.

Any idea?

Thanks, bert

**Comment by bert2002** [comment]
It works with the binaries you provide in [v0.2.3](https://github.com/persistenceOne/persistenceCore/releases/tag/v0.2.3). Is that version sufficient to run a validator or is there an upgrade path?

Thanks,
bert
