### ISSUE TITLE
v4 Upgrade panic: epoch with identifier day already exists

### ISSUE THREAD

**Issue by bert2002** [persistenceOne/persistenceCore#147]
Hi,
we upgraded our node to `v4.0.0` due to the fork, but it stops working with the following error:

```
$ /opt/persistence/build/persistenceCore start
3:28AM INF starting node with ABCI Tendermint in-process
3:28AM INF service start impl=multiAppConn module=proxy msg={}
3:28AM INF service start connection=query impl=localClient module=abci-client msg={}
3:28AM INF service start connection=snapshot impl=localClient module=abci-client msg={}
3:28AM INF service start connection=mempool impl=localClient module=abci-client msg={}
3:28AM INF service start connection=consensus impl=localClient module=abci-client msg={}
3:28AM INF service start impl=EventBus module=events msg={}
3:28AM INF service start impl=PubSub module=pubsub msg={}
3:28AM INF service start impl=IndexerService module=txindex msg={}
3:28AM INF ABCI Handshake App Info hash="�������M}I}�\v��MR\x15�\r�)�r��\x1dh\x7f2\v1" height=8589499 module=consensus protocol-version=0 software-version=v4.0.0
3:28AM INF ABCI Replay Blocks appHeight=8589499 module=consensus stateHeight=8589499 storeHeight=8589500
3:28AM INF Replay last block using real app module=consensus
3:28AM INF applying upgrade "v4" at height: 8589500
3:28AM INF start to run module migrations...
3:28AM INF adding a new module: epochs
3:28AM INF adding a new module: ibchooker   
3:28AM INF adding a new module: interchainquery
3:28AM INF adding a new module: lscosmos
3:28AM INF migrating module transfer from version 1 to version 2
3:28AM INF Starting new epoch with identifier day epoch number 1 module=x/epochs
3:28AM INF Starting new epoch with identifier hour epoch number 1 module=x/epochs
3:28AM INF Starting new epoch with identifier week epoch number 1 module=x/epochs
3:28AM INF minted coins from module account amount=6934339uxprt from=mint module=x/bank
3:28AM INF executed block height=8589500 module=consensus num_invalid_txs=0 num_valid_txs=0
3:28AM INF commit synced commit=436F6D6D697449447B5B3534203135362034342031373520323337203230362031393120313639203230342032313520363520323332203020313134203134312031333520323038203
8382032333520323530203230382038203231392036203231312039392032323620342031323220343620313039203136345D3A3833313042437D
3:28AM INF committed state app_hash=369C2CAFEDCEBFA9CCD741E800728D87D058EBFAD008DB06D363E2047A2E6DA4 height=8589500 module=consensus num_txs=0
3:28AM INF Completed ABCI Handshake - Tendermint and App are synced appHash="�������M}I}�\v��MR\x15�\r�)�r��\x1dh\x7f2\v1" appHeight=8589499 module=consensus
3:28AM INF Version info block=11 p2p=8 tendermint_version=v0.34.21
3:28AM INF This node is not a validator addr=95150F9FF0EEC8CD4F54A73AF2D589195FDB4961 module=consensus pubKey=PADJxqUp2WogqM+ysDgcfVqAqxGmXA1amItuFinh5BE=
3:28AM INF indexed block height=8589500 module=txindex
3:28AM INF P2P Node ID ID=1c880e0f615e743310f4619f6711e9d88448d3bd file=/home/persistence/.persistenceCore/config/node_key.json module=p2p
3:28AM INF Adding persistent peers addrs=[] module=p2p
3:28AM INF Adding unconditional peer ids ids=[] module=p2p
3:28AM INF Add our address to book addr={"id":"1c880e0f615e743310f4619f6711e9d88448d3bd","ip":"54.169.213.13","port":26656} book=/home/persistence/.persistenceCore/config/addrbook
.json module=p2p
3:28AM INF Add our address to book addr={"id":"1c880e0f615e743310f4619f6711e9d88448d3bd","ip":"0.0.0.0","port":26656} book=/home/persistence/.persistenceCore/config/addrbook.json 
module=p2p
3:28AM INF service start impl=Node msg={}   
3:28AM INF Starting pprof server laddr=localhost:6060
3:28AM INF service start impl="P2P Switch" module=p2p msg={}
3:28AM INF serve module=rpc-server msg={}   
3:28AM INF service start impl=BlockchainReactor module=blockchain msg={}
3:28AM INF service start impl=BlockPool module=blockchain msg={}
3:28AM INF service start impl=ConsensusReactor module=consensus msg={}
3:28AM INF Reactor  module=consensus waitSync=true
3:28AM INF service start impl=Evidence module=evidence msg={}
3:28AM INF service start impl=StateSync module=statesync msg={}
3:28AM INF service start impl=PEX module=pex msg={}
3:28AM INF service start book=/home/persistence/.persistenceCore/config/addrbook.json impl=AddrBook module=p2p msg={}
3:28AM INF Saving AddrBook to file book=/home/persistence/.persistenceCore/config/addrbook.json module=p2p size=384
3:28AM INF Ensure peers module=pex numDialing=0 numInPeers=0 numOutPeers=0 numToDial=10
3:28AM INF Dialing peer address={"id":"4f15365dc8eb8088e04acd7683f0709b6f431869","ip":"161.35.215.171","port":26656} module=p2p
3:28AM INF Dialing peer address={"id":"bdfc3daa2e3355470b7c4103af30e2a6b303a9a8","ip":"65.108.80.23","port":26656} module=p2p
3:28AM INF Dialing peer address={"id":"bb802fbb356d272ccad17f36113e6940c561f6ea","ip":"35.200.177.9","port":26656} module=p2p
3:28AM INF Dialing peer address={"id":"1eb7be2acf4803d3b02892a3c8c5d0c50a3058fe","ip":"65.108.80.23","port":26656} module=p2p
3:28AM INF Dialing peer address={"id":"97e4468ac589eac505a800411c635b14511a61bb","ip":"5.9.239.237","port":26656} module=p2p
3:28AM INF Dialing peer address={"id":"72e6c8d0a7edfe0b914ab7ee5606251d56cda2fb","ip":"99.79.48.184","port":26656} module=p2p
3:28AM INF Dialing peer address={"id":"d4ff6ea6546aecd8cac0df76e4dd3838f3ab2d9f","ip":"15.207.18.221","port":26656} module=p2p
3:28AM INF Dialing peer address={"id":"555f3a872b97707d67a5253cbd99d1cba7adc446","ip":"65.21.136.58","port":16656} module=p2p
3:28AM INF Dialing peer address={"id":"d154cce30b4b5aee1dc968004902159b67fa3f67","ip":"147.182.237.118","port":31183} module=p2p
3:28AM INF Dialing peer address={"id":"83ffa913850aa299e549a0bc0248d93408778bd5","ip":"54.66.162.205","port":26656} module=p2p
3:28AM INF starting API server... module=api-server
3:28AM INF serve module=api-server msg={}   
3:28AM INF service start impl="Peer{MConn{5.9.239.237:26656} 97e4468ac589eac505a800411c635b14511a61bb out}" module=p2p msg={} peer={"id":"97e4468ac589eac505a800411c635b14511a61bb"
,"ip":"5.9.239.237","port":26656}
3:28AM INF service start impl=MConn{5.9.239.237:26656} module=p2p msg={} peer={"id":"97e4468ac589eac505a800411c635b14511a61bb","ip":"5.9.239.237","port":26656}
3:28AM INF Added peer module=p2p peer={"Data":{},"Logger":{}}
3:28AM INF Connection is closed @ recvRoutine (likely by the other side) conn={"Logger":{}} module=p2p peer={"id":"97e4468ac589eac505a800411c635b14511a61bb","ip":"5.9.239.237","port":26656}
3:28AM INF service stop impl={"Logger":{}} module=p2p msg={} peer={"id":"97e4468ac589eac505a800411c635b14511a61bb","ip":"5.9.239.237","port":26656}
3:28AM ERR Stopping peer for error err=EOF module=p2p peer={"Data":{},"Logger":{}}
3:28AM INF service stop impl={"Data":{},"Logger":{}} module=p2p msg={} peer={"id":"97e4468ac589eac505a800411c635b14511a61bb","ip":"5.9.239.237","port":26656}
3:28AM INF service start impl="Peer{MConn{157.90.180.62:52274} d68cba170d40f7b36962a5e44048e11b55db8375 in}" module=p2p msg={} peer={"id":"d68cba170d40f7b36962a5e44048e11b55db8375","ip":"157.90.180.62","port":52274}
3:28AM INF service start impl=MConn{157.90.180.62:52274} module=p2p msg={} peer={"id":"d68cba170d40f7b36962a5e44048e11b55db8375","ip":"157.90.180.62","port":52274}
3:28AM INF Added peer module=p2p peer={"Data":{},"Logger":{}}
3:28AM INF applying upgrade "v4" at height: 8589500
3:28AM INF start to run module migrations...
panic: epoch with identifier day already exists


goroutine 33 [running]:
github.com/persistenceOne/persistence-sdk/x/epochs/keeper.Keeper.InitGenesis(...)
        github.com/persistenceOne/persistence-sdk@v1.0.0/x/epochs/keeper/genesis.go:14
github.com/persistenceOne/persistence-sdk/x/epochs.AppModule.InitGenesis({{}, {{_, _}, {_, _}}}, {{0x2726768, 0xc00012e000}, {0x2737980, 0xc039a75480}, {{0xb, ...}, ...}, ...}, ...)
        github.com/persistenceOne/persistence-sdk@v1.0.0/x/epochs/module.go:151 +0x285
github.com/cosmos/cosmos-sdk/types/module.Manager.RunMigrations({0xc0051074d0, {0xc00050c4e0, 0x19, 0x19}, {0xc000603d40, 0x19, 0x19}, {0xc00050c1a0, 0x19, 0x19}, ...}, ...)
        github.com/cosmos/cosmos-sdk@v0.45.10-0.20221014225501-18eaf090ca1c/types/module/module.go:467 +0x662
github.com/persistenceOne/persistenceCore/v4/app.NewApplication.func1({{0x2726768, 0xc00012e000}, {0x2737980, 0xc039a75480}, {{0xb, 0x0}, {0xc016ca2ce0, 0x6}, 0x8310bd, {0x34713d4c, ...}, ...}, ...}, ...)
        github.com/persistenceOne/persistenceCore/v4/app/app.go:810 +0x145
github.com/cosmos/cosmos-sdk/x/upgrade/keeper.Keeper.ApplyUpgrade({{0xc001176e10, 0x22}, 0xc005052ae0, {0x27115a8, 0xc005104c00}, {0x2735a80, 0xc001194d00}, 0xc005106f90, {0x270b1a0, 0xc0003ba1c0}, ...}, ...)
        github.com/cosmos/cosmos-sdk@v0.45.10-0.20221014225501-18eaf090ca1c/x/upgrade/keeper/keeper.go:340 +0x1be
github.com/cosmos/cosmos-sdk/x/upgrade.BeginBlocker({{0xc001176e10, 0x22}, 0xc005052ae0, {0x27115a8, 0xc005104c00}, {0x2735a80, 0xc001194d00}, 0xc005106f90, {0x270b1a0, 0xc0003ba1c0}, ...}, ...)
        github.com/cosmos/cosmos-sdk@v0.45.10-0.20221014225501-18eaf090ca1c/x/upgrade/abci.go:76 +0xa45
github.com/cosmos/cosmos-sdk/x/upgrade.AppModule.BeginBlock(...)
        github.com/cosmos/cosmos-sdk@v0.45.10-0.20221014225501-18eaf090ca1c/x/upgrade/module.go:130
github.com/cosmos/cosmos-sdk/types/module.(*Manager).BeginBlock(_, {{0x2726768, 0xc00012e000}, {0x2737980, 0xc039a75480}, {{0xb, 0x0}, {0xc016ca2ce0, 0x6}, 0x8310bd, ...}, ...}, ...)
        github.com/cosmos/cosmos-sdk@v0.45.10-0.20221014225501-18eaf090ca1c/types/module/module.go:491 +0x3bb
github.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).BeginBlock(_, {{0xc043f649e0, 0x20, 0x20}, {{0xb, 0x0}, {0xc016ca2ce0, 0x6}, 0x8310bd, {0x34713d4c, ...}, ...}, ...})
        github.com/cosmos/cosmos-sdk@v0.45.10-0.20221014225501-18eaf090ca1c/baseapp/abci.go:177 +0x97b
github.com/tendermint/tendermint/abci/client.(*localClient).BeginBlockSync(_, {{0xc043f649e0, 0x20, 0x20}, {{0xb, 0x0}, {0xc016ca2ce0, 0x6}, 0x8310bd, {0x34713d4c, ...}, ...}, ...})
        github.com/tendermint/tendermint@v0.34.21/abci/client/local_client.go:280 +0x118
github.com/tendermint/tendermint/proxy.(*appConnConsensus).BeginBlockSync(_, {{0xc043f649e0, 0x20, 0x20}, {{0xb, 0x0}, {0xc016ca2ce0, 0x6}, 0x8310bd, {0x34713d4c, ...}, ...}, ...})
        github.com/tendermint/tendermint@v0.34.21/proxy/app_conn.go:81 +0x55
github.com/tendermint/tendermint/state.execBlockOnProxyApp({0x2727878?, 0xc04937b9e0}, {0x272f2d0, 0xc00bd58a10}, 0xc038ddc3c0, {0x2736e08, 0xc017188360}, 0x8310bc?)
        github.com/tendermint/tendermint@v0.34.21/state/execution.go:307 +0x3dd
github.com/tendermint/tendermint/state.(*BlockExecutor).ApplyBlock(_, {{{0xb, 0x0}, {0xc0493a9ac0, 0x8}}, {0xc0493a9ac8, 0x6}, 0x1, 0x8310bc, {{0xc0493b50c0, ...}, ...}, ...}, ...)
        github.com/tendermint/tendermint@v0.34.21/state/execution.go:140 +0x171
github.com/tendermint/tendermint/blockchain/v0.(*BlockchainReactor).poolRoutine(0xc0003bac40, 0x0)
        github.com/tendermint/tendermint@v0.34.21/blockchain/v0/reactor.go:404 +0xbda
created by github.com/tendermint/tendermint/blockchain/v0.(*BlockchainReactor).OnStart
        github.com/tendermint/tendermint@v0.34.21/blockchain/v0/reactor.go:110 +0x7a
```

Please let us know how we can continue or if there is fix available?

Thanks,
bert

**Comment by bert2002** [comment]
I worked with a different snapshot and it worked. This just means it will not be possible to sync from genesis with the current software release.
