### ISSUE TITLE
can't sync from scratch

### ISSUE THREAD

**Issue by lsdbitrue** [persistenceOne/persistenceCore#98]
Version: latest commit

I followed this document for deployment

https://github.com/persistenceOne/networks/blob/master/core-1/README.md

```
11:13AM INF Error reconnecting to peer. Trying again addr={"id":"ecc00c5a7abd057ea5ca4a94c48d1d937bbab34a","ip":"34.118.19.56","port":26656} err="auth failure: secret conn failed: read tcp 10.225.23.98:53762->34.118.19.56:26656: i/o timeout" module=p2p tries=14
11:13AM INF Stopping Node service impl={"Logger":{}}
11:13AM INF Stopping Node
11:13AM INF Stopping EventBus service impl={"Logger":{}} module=events
11:13AM INF Stopping PubSub service impl={"Logger":{}} module=pubsub
11:13AM INF Stopping IndexerService service impl={"Logger":{}} module=txindex
11:13AM INF Stopping P2P Switch service impl={"Logger":{}} module=p2p
11:13AM INF Stopping Consensus service impl={"Logger":{},"Metrics":{"BlockIntervalSeconds":{},"BlockParts":{},"BlockSizeBytes":{},"ByzantineValidators":{},"ByzantineValidatorsPower":{},"CommittedHeight":{},"FastSyncing":{},"FullPrevoteMessageDelay":{},"Height":{},"MissingValidators":{},"MissingValidatorsPower":{},"NumTxs":{},"QuorumPrevoteMessageDelay":{},"Rounds":{},"StateSyncing":{},"TotalTxs":{},"ValidatorLastSignedHeight":{},"ValidatorMissedBlocks":{},"ValidatorPower":{},"Validators":{},"ValidatorsPower":{}},"Switch":{"Logger":{}}} module=consensus
11:13AM ERR Not stopping State service -- has not been started yet impl={"Logger":{},"commit_round":-1,"commit_time":"0001-01-01T00:00:00Z","height":1,"last_commit":null,"last_validators":{"proposer":null,"validators":null},"locked_block":null,"locked_block_parts":null,"locked_round":-1,"proposal":null,"proposal_block":null,"proposal_block_parts":null,"round":0,"start_time":"2022-08-03T11:03:31.461804265Z","step":1,"triggered_timeout_precommit":false,"valid_block":null,"valid_block_parts":null,"valid_round":-1,"validators":{"proposer":{"address":"6EE58A5199507348FAFC3DCE390E570D4748E914","proposer_priority":-68311,"pub_key":"l3AVhw8K/XXeZdB25sJNkvykxm+yBL4E6g7CuelCaeE=","voting_power":100000},"validators":[{"address":"6EE58A5199507348FAFC3DCE390E570D4748E914","proposer_priority":-68311,"pub_key":"l3AVhw8K/XXeZdB25sJNkvykxm+yBL4E6g7CuelCaeE=","voting_power":100000},{"address":"0F6A455DDFDCF91728829EF6EB83DD938BC140C7","proposer_priority":10000,"pub_key":"rxpY904CY7AZhlx/1/x5ukFccoKSr2VQ3Q0q5xshlYI=","voting_power":10000},{"address":"11A66ECE1E4945CA3AF1A2F034CE4C243AB5E1A7","proposer_priority":10000,"pub_key":"EbGdLmCheeONbAuKd3n+uUfpimdA8w3D1UXDb2lSGIU=","voting_power":10000},{"address":"701E76605B60379A7BED520D341ECC758EF7D034","proposer_priority":10000,"pub_key":"FLZFXsWnQIB6ZAS4GsmnECre+PN3p8XhfgH47NZSy/g=","voting_power":10000},{"address":"BBDE53946D16FB13F14013FC8E84B1E3B53AE9E7","proposer_priority":10000,"pub_key":"YmQrPBwSixQKDjR3r0X2W54Is3O3A/6r3cBlv8HYsho=","voting_power":10000},{"address":"EE0BB613EFCC25A7813424616DE6E9F7FBDA3004","proposer_priority":10000,"pub_key":"uOSl0fQekJvEVyrVJBLl1h5H8f7hZS7Lbl2LgtFIpXc=","voting_power":10000},{"address":"F7CBFC33C088FFC41FF6EB94A2DC7F839F0CC341","proposer_priority":10000,"pub_key":"io+JntVbbb5UbO/lgu4KgVcbH3mH2P4o8/orAHedosQ=","voting_power":10000},{"address":"0654396ACC5A99707042E7B63CC9069093321B31","proposer_priority":1000,"pub_key":"fGXhkQSMrkMJBfXp5U3hGgRDxgxJQN1WYAeFXxEwqwY=","voting_power":1000},{"address":"2B93C9D21C620899B8E4DD9C6EA03F5A103003EE","proposer_priority":1000,"pub_key":"SHQman+tnUbNbOeTaLUHP28Ca12l9FUJn1MP9GJMdqg=","voting_power":1000},{"address":"A48C16EDA94907EC68BEFFE39B0C813F57DA5110","proposer_priority":1000,"pub_key":"6wnsNKw6yiBmO0ODZNotG1Gm6XxbUQFP6Pc03naBH1I=","voting_power":1000},{"address":"D0678C138BE695B022CCE9A8DD852A1F0E2AA4DB","proposer_priority":1000,"pub_key":"Htt/d9NixxZWAzPEy6NFpz6LOHTnjW35viC1QJxkwoA=","voting_power":1000},{"address":"E43D037D7467F7B7EC24250E936A91350C87C942","proposer_priority":1000,"pub_key":"9Zp68muRuuMjt8lW4paIJoSn/oBF7VmUlgR9OvU/AJQ=","voting_power":1000},{"address":"E7E54BC75BD8A4F687AD5F450902EF9EDA5BDF25","proposer_priority":1000,"pub_key":"QjFwv9M/wdnw7SxQyp0JCdoJ01cbQKg/5RN4hOzjD4w=","voting_power":1000},{"address":"F2BE9467842612AF5B4CDED7A3AC830E16D34D7F","proposer_priority":1000,"pub_key":"6Rv4uZ0bSjZYf8hPtnijNg5WnLjDrZioFvPpmCBetUw=","voting_power":1000},{"address":"B2B1B16933D96D3C95249FCBD900A15C1B3601A9","proposer_priority":999,"pub_key":"gZpXSPJtBpI5DiooynoNaeNv/VvkC+zhrAlZv4pHKQk=","voting_power":999},{"address":"9E2FB0553D7ED86714C308D14F4E734E8570C230","proposer_priority":200,"pub_key":"VF1EBZzV++aSm8/1wfGM9J6Uaq4Nnr2he9b2lDcg0JM=","voting_power":200},{"address":"00DE69012E145D844F0976F4CA04AEBC7D21FDBE","proposer_priority":100,"pub_key":"PM4cI23ibujVo/NyaATPGzlRZVuMnxg2DpbA+T830ek=","voting_power":100},{"address":"0EEFAA96C91E32584A8591488966FFE77609E1F4","proposer_priority":10,"pub_key":"QyMlPjpx0+wRSxylnb/INpYodeEHjKtmyayP8WAElg8=","voting_power":10},{"address":"A0CF8AA8871F7EFEBB2EBCAF94167F64683E7166","proposer_priority":1,"pub_key":"qudwkDdojj6w3Vs76NciHBQd7EAlGBxS48dPHq/5tAs=","voting_power":1},{"address":"E94F405D330DCC9BD94B16CF9F7E0B6183328E05","proposer_priority":1,"pub_key":"QAHOs7+adF9ifM7h1TESZrZaw15W2dwREpiiR+BVpCg=","voting_power":1}]},"votes":[{"precommits":["nil-Vote","nil-Vote","nil-Vote","nil-Vote","nil-Vote","nil-Vote","nil-Vote","nil-Vote","nil-Vote","nil-Vote","nil-Vote","nil-Vote","nil-Vote","nil-Vote","nil-Vote","nil-Vote","nil-Vote","nil-Vote","nil-Vote","nil-Vote"],"precommits_bit_array":"BA{20:____________________} 0/168311 = 0.00","prevotes":["nil-Vote","nil-Vote","nil-Vote","nil-Vote","nil-Vote","nil-Vote","nil-Vote","nil-Vote","nil-Vote","nil-Vote","nil-Vote","nil-Vote","nil-Vote","nil-Vote","nil-Vote","nil-Vote","nil-Vote","nil-Vote","nil-Vote","nil-Vote"],"prevotes_bit_array":"BA{20:____________________} 0/168311 = 0.00","round":0}]} module=consensus
11:13AM ERR Error stopping consensus state err="not started" module=consensus
11:13AM INF Stopping Evidence service impl={"Logger":{},"Switch":{"Logger":{}}} module=evidence
11:13AM INF Stopping StateSync service impl={"Logger":{},"Switch":{"Logger":{}}} module=statesync
11:13AM INF Stopping PEX service impl={"Logger":{},"Switch":{"Logger":{}}} module=pex
11:13AM INF Stopping AddrBook service book=/root/.persistenceCore/config/addrbook.json impl={"Logger":{}} module=p2p
11:13AM INF Stopping Mempool service impl={"Logger":{},"Switch":{"Logger":{}}} module=mempool
11:13AM INF Stopping BlockchainReactor service impl={"Logger":{},"Switch":{"Logger":{}}} module=blockchain
11:13AM INF Saving AddrBook to file book=/root/.persistenceCore/config/addrbook.json module=p2p size=13
11:13AM INF Stopping BlockPool service impl={"Logger":{}} module=blockchain
11:13AM INF Closing rpc listener listener={"Listener":{}}
11:13AM INF RPC HTTP server stopped err="accept tcp [::]:26657: use of closed network connection" module=rpc-server
11:13AM ERR Error serving server err="accept tcp [::]:26657: use of closed network connection"
11:13AM ERR Stopped accept routine, as transport is closed module=p2p numPeers=0
11:13AM INF exiting...
```

**Comment by lsdbitrue** [comment]
There are many p2p errors

```
1:15AM INF Starting MConnection service impl=MConn{178.62.103.7:26656} module=p2p peer={"id":"01102f3c84e6602e30e1e39498e242cbb60a0b73","ip":"178.62.103.7","port":26656}
11:15AM INF Added peer module=p2p peer={"Data":{},"Logger":{}}
11:15AM INF Connection is closed @ recvRoutine (likely by the other side) conn={"Logger":{}} module=p2p peer={"id":"01102f3c84e6602e30e1e39498e242cbb60a0b73","ip":"178.62.103.7","port":26656}
11:15AM INF Stopping MConnection service impl={"Logger":{}} module=p2p peer={"id":"01102f3c84e6602e30e1e39498e242cbb60a0b73","ip":"178.62.103.7","port":26656}
11:15AM ERR Stopping peer for error err=EOF module=p2p peer={"Data":{},"Logger":{}}
11:15AM INF Stopping Peer service impl={"Data":{},"Logger":{}} module=p2p peer={"id":"01102f3c84e6602e30e1e39498e242cbb60a0b73","ip":"178.62.103.7","port":26656}
11:15AM INF Reconnecting to peer addr={"id":"01102f3c84e6602e30e1e39498e242cbb60a0b73","ip":"178.62.103.7","port":26656} module=p2p
11:15AM INF Dialing peer address={"id":"01102f3c84e6602e30e1e39498e242cbb60a0b73","ip":"178.62.103.7","port":26656} module=p2p
11:15AM INF Error reconnecting to peer. Trying again addr={"id":"b19a3cf4d9938b41539729d027bf2e3c1a4e1fbb","ip":"85.214.130.157","port":26656} err="auth failure: secret conn failed: read tcp 10.225.23.98:43260->85.214.130.157:26656: i/o timeout" module=p2p tries=10
```

**Comment by puneet2019** [comment]
@lsdbitrue I would suggest asking validators for latest peer addresses on discord, then just `persistenceCore unsafe-reset-all` (please backup `priv_validator_key.json` before you reset) and start chain with active peers

**Comment by lsdbitrue** [comment]
@puneet2019 Thanks for reply, could you team provide the latest peer list?

**Comment by lsdbitrue** [comment]
What's the error? I'm using this genesis file https://github.com/persistenceOne/networks/blob/master/core-1/final_genesis.json

```
6:40AM INF starting ABCI with Tendermint
6:40AM ERR WARNING: The minimum-gas-prices config in app.toml is set to the empty string. This defaults to 0 in the current version, but will error in the next version (SDK v0.45). Please explicitly put the desired minimum-gas-prices in your app.toml.
6:40AM INF Starting multiAppConn service impl=multiAppConn module=proxy
6:40AM INF Starting localClient service connection=query impl=localClient module=abci-client
6:40AM INF Starting localClient service connection=snapshot impl=localClient module=abci-client
6:40AM INF Starting localClient service connection=mempool impl=localClient module=abci-client
6:40AM INF Starting localClient service connection=consensus impl=localClient module=abci-client
6:40AM INF Starting EventBus service impl=EventBus module=events
6:40AM INF Starting PubSub service impl=PubSub module=pubsub
6:40AM INF Starting IndexerService service impl=IndexerService module=txindex
6:40AM INF ABCI Handshake App Info hash= height=0 module=consensus protocol-version=0 software-version=2020.1.4
6:40AM INF ABCI Replay Blocks appHeight=0 module=consensus stateHeight=0 storeHeight=0
6:40AM INF asserting crisis invariants inv=0/11 module=x/crisis name=bank/nonnegative-outstanding
6:40AM INF asserting crisis invariants inv=1/11 module=x/crisis name=bank/total-supply
6:40AM INF asserting crisis invariants inv=2/11 module=x/crisis name=gov/module-account
6:40AM INF asserting crisis invariants inv=3/11 module=x/crisis name=distribution/nonnegative-outstanding
6:40AM INF asserting crisis invariants inv=4/11 module=x/crisis name=distribution/can-withdraw
6:40AM INF asserting crisis invariants inv=5/11 module=x/crisis name=distribution/reference-count
6:40AM INF asserting crisis invariants inv=6/11 module=x/crisis name=distribution/module-account
6:40AM INF asserting crisis invariants inv=7/11 module=x/crisis name=staking/module-accounts
6:40AM INF asserting crisis invariants inv=8/11 module=x/crisis name=staking/nonnegative-power
6:40AM INF asserting crisis invariants inv=9/11 module=x/crisis name=staking/positive-delegation
6:40AM INF asserting crisis invariants inv=10/11 module=x/crisis name=staking/delegator-shares
6:40AM INF asserted all invariants duration=1.144486 height=0 module=x/crisis
6:40AM INF created new capability module=ibc name=ports/transfer
6:40AM INF port binded module=x/ibc/port port=transfer
6:40AM INF claimed capability capability=1 module=transfer name=ports/transfer
6:40AM INF Completed ABCI Handshake - Tendermint and App are synced appHash= appHeight=0 module=consensus
6:40AM INF Version info block=11 p2p=8 tendermint_version=v0.34.14
6:40AM INF This node is not a validator addr=B3184BC84EE79399F0A3288D91B4D930ACF7DD00 module=consensus pubKey=yOhh/tWe83aUh5JV4H2bIC03iSUqoFro4lmD/5bPfhg=
6:40AM INF P2P Node ID ID=e0ea1d963be941495142972b0e633b6105c7f96f file=/root/.persistenceCore/config/node_key.json module=p2p
6:40AM INF Adding persistent peers addrs=["e9283949d8cd716f7987c9f7c359cc49c4e97e0d@persistence-mainnet-statesync.allthatnode.com:26656","646d0ad08c408f93276f90cd29d4e410e2d60f63@xprt.paranorm.pro:25656"] module=p2p
6:40AM INF Adding unconditional peer ids ids=[] module=p2p
6:40AM INF Add our address to book addr={"id":"e0ea1d963be941495142972b0e633b6105c7f96f","ip":"0.0.0.0","port":26656} book=/root/.persistenceCore/config/addrbook.json module=p2p
6:40AM INF Starting Node service impl=Node
6:40AM INF Starting pprof server laddr=localhost:6060
6:40AM INF Starting P2P Switch service impl="P2P Switch" module=p2p
6:40AM INF Starting Evidence service impl=Evidence module=evidence
6:40AM INF Starting StateSync service impl=StateSync module=statesync
6:40AM INF Starting PEX service impl=PEX module=pex
6:40AM INF Starting RPC HTTP server on [::]:26657 module=rpc-server
6:40AM INF Starting AddrBook service book=/root/.persistenceCore/config/addrbook.json impl=AddrBook module=p2p
6:40AM INF Starting Mempool service impl=Mempool module=mempool
6:40AM INF Starting BlockchainReactor service impl=BlockchainReactor module=blockchain
6:40AM INF Starting BlockPool service impl=BlockPool module=blockchain
6:40AM INF Starting Consensus service impl=ConsensusReactor module=consensus
6:40AM INF Reactor  module=consensus waitSync=true
6:40AM INF Ensure peers module=pex numDialing=0 numInPeers=0 numOutPeers=0 numToDial=10
6:40AM INF No addresses to dial. Falling back to seeds module=pex
6:40AM INF Dialing peer address={"id":"ac7e6aab726e842b92c06b8ebbf5a3616872ee80","ip":"128.1.133.107","port":26656} module=p2p
6:40AM INF Saving AddrBook to file book=/root/.persistenceCore/config/addrbook.json module=p2p size=2
6:40AM INF Dialing peer address={"id":"e9283949d8cd716f7987c9f7c359cc49c4e97e0d","ip":"195.201.167.113","port":26656} module=p2p
6:40AM ERR Error dialing seed err="dial tcp 128.1.133.107:26656: i/o timeout" module=p2p seed={"id":"ac7e6aab726e842b92c06b8ebbf5a3616872ee80","ip":"128.1.133.107","port":26656}
6:40AM INF Dialing peer address={"id":"a92ff1da2020e5cbc9b05527e9e39c34a84e8a27","ip":"34.72.57.218","port":26656} module=p2p
6:40AM INF Dialing peer address={"id":"646d0ad08c408f93276f90cd29d4e410e2d60f63","ip":"193.34.144.156","port":25656} module=p2p
6:40AM INF Starting Peer service impl="Peer{MConn{193.34.144.156:25656} 646d0ad08c408f93276f90cd29d4e410e2d60f63 out}" module=p2p peer={"id":"646d0ad08c408f93276f90cd29d4e410e2d60f63","ip":"193.34.144.156","port":25656}
6:40AM INF Starting MConnection service impl=MConn{193.34.144.156:25656} module=p2p peer={"id":"646d0ad08c408f93276f90cd29d4e410e2d60f63","ip":"193.34.144.156","port":25656}
6:40AM INF Added peer module=p2p peer={"Data":{},"Logger":{}}
6:40AM ERR Error dialing peer err="auth failure: secret conn failed: read tcp 172.17.0.2:53394->195.201.167.113:26656: i/o timeout" module=p2p
6:40AM INF Reconnecting to peer addr={"id":"e9283949d8cd716f7987c9f7c359cc49c4e97e0d","ip":"195.201.167.113","port":26656} module=p2p
6:40AM INF Dialing peer address={"id":"e9283949d8cd716f7987c9f7c359cc49c4e97e0d","ip":"195.201.167.113","port":26656} module=p2p
6:40AM ERR Error dialing seed err="auth failure: secret conn failed: read tcp 172.17.0.2:37974->34.72.57.218:26656: i/o timeout" module=p2p seed={"id":"a92ff1da2020e5cbc9b05527e9e39c34a84e8a27","ip":"34.72.57.218","port":26656}
6:40AM INF Dialing peer address={"id":"b19a3cf4d9938b41539729d027bf2e3c1a4e1fbb","ip":"85.214.130.157","port":26656} module=p2p
6:40AM INF Error reconnecting to peer. Trying again addr={"id":"e9283949d8cd716f7987c9f7c359cc49c4e97e0d","ip":"195.201.167.113","port":26656} err="auth failure: secret conn failed: read tcp 172.17.0.2:53396->195.201.167.113:26656: i/o timeout" module=p2p tries=0
6:40AM ERR Error dialing seed err="auth failure: secret conn failed: read tcp 172.17.0.2:42734->85.214.130.157:26656: i/o timeout" module=p2p seed={"id":"b19a3cf4d9938b41539729d027bf2e3c1a4e1fbb","ip":"85.214.130.157","port":26656}
6:40AM INF Dialing peer address={"id":"60385a36ea72a2985bd8450c95b8df8be2adebb8","ip":"54.95.235.242","port":26656} module=p2p
6:40AM ERR Error dialing seed err="dial tcp 54.95.235.242:26656: i/o timeout" module=p2p seed={"id":"60385a36ea72a2985bd8450c95b8df8be2adebb8","ip":"54.95.235.242","port":26656}
6:40AM INF Dialing peer address={"id":"cfb529bd0325fc884296518655f1f315bc42dd0c","ip":"185.144.83.165","port":26656} module=p2p
6:41AM ERR Error dialing seed err="auth failure: secret conn failed: read tcp 172.17.0.2:41054->185.144.83.165:26656: i/o timeout" module=p2p seed={"id":"cfb529bd0325fc884296518655f1f315bc42dd0c","ip":"185.144.83.165","port":26656}
6:41AM INF Dialing peer address={"id":"7b9839cd3e994c44cbd747d1ddc51ee695f60e58","ip":"157.90.134.48","port":26656} module=p2p
6:41AM INF Dialing peer address={"id":"e9283949d8cd716f7987c9f7c359cc49c4e97e0d","ip":"195.201.167.113","port":26656} module=p2p
6:41AM ERR Error dialing seed err="auth failure: secret conn failed: read tcp 172.17.0.2:37244->157.90.134.48:26656: i/o timeout" module=p2p seed={"id":"7b9839cd3e994c44cbd747d1ddc51ee695f60e58","ip":"157.90.134.48","port":26656}
6:41AM INF Dialing peer address={"id":"ecc00c5a7abd057ea5ca4a94c48d1d937bbab34a","ip":"34.118.19.56","port":26656} module=p2p
6:41AM INF Error reconnecting to peer. Trying again addr={"id":"e9283949d8cd716f7987c9f7c359cc49c4e97e0d","ip":"195.201.167.113","port":26656} err="auth failure: secret conn failed: read tcp 172.17.0.2:53398->195.201.167.113:26656: i/o timeout" module=p2p tries=1
6:41AM ERR Error dialing seed err="auth failure: secret conn failed: read tcp 172.17.0.2:60176->34.118.19.56:26656: i/o timeout" module=p2p seed={"id":"ecc00c5a7abd057ea5ca4a94c48d1d937bbab34a","ip":"34.118.19.56","port":26656}
6:41AM INF Dialing peer address={"id":"e15524629aee25fea01f62d26c4e062bfda94b70","ip":"35.247.171.7","port":26656} module=p2p
6:41AM ERR Error dialing seed err="auth failure: secret conn failed: read tcp 172.17.0.2:41718->35.247.171.7:26656: i/o timeout" module=p2p seed={"id":"e15524629aee25fea01f62d26c4e062bfda94b70","ip":"35.247.171.7","port":26656}
6:41AM INF Dialing peer address={"id":"b9dab7a1a5ffd16d43b19e40a8020db84e8dfffd","ip":"3.14.116.246","port":44456} module=p2p
6:41AM ERR Error dialing seed err="dial tcp 3.14.116.246:44456: i/o timeout" module=p2p seed={"id":"b9dab7a1a5ffd16d43b19e40a8020db84e8dfffd","ip":"3.14.116.246","port":44456}
6:41AM INF Dialing peer address={"id":"01102f3c84e6602e30e1e39498e242cbb60a0b73","ip":"178.62.103.7","port":26656} module=p2p
6:41AM INF Starting Peer service impl="Peer{MConn{178.62.103.7:26656} 01102f3c84e6602e30e1e39498e242cbb60a0b73 out}" module=p2p peer={"id":"01102f3c84e6602e30e1e39498e242cbb60a0b73","ip":"178.62.103.7","port":26656}
6:41AM INF Starting MConnection service impl=MConn{178.62.103.7:26656} module=p2p peer={"id":"01102f3c84e6602e30e1e39498e242cbb60a0b73","ip":"178.62.103.7","port":26656}
6:41AM INF Added peer module=p2p peer={"Data":{},"Logger":{}}
6:41AM INF Connection is closed @ recvRoutine (likely by the other side) conn={"Logger":{}} module=p2p peer={"id":"01102f3c84e6602e30e1e39498e242cbb60a0b73","ip":"178.62.103.7","port":26656}
6:41AM INF Stopping MConnection service impl={"Logger":{}} module=p2p peer={"id":"01102f3c84e6602e30e1e39498e242cbb60a0b73","ip":"178.62.103.7","port":26656}
6:41AM ERR Stopping peer for error err=EOF module=p2p peer={"Data":{},"Logger":{}}
6:41AM INF Stopping Peer service impl={"Data":{},"Logger":{}} module=p2p peer={"id":"01102f3c84e6602e30e1e39498e242cbb60a0b73","ip":"178.62.103.7","port":26656}
6:41AM INF Stopping gossipVotesRoutine for peer module=consensus peer={"Data":{},"Logger":{}}
6:41AM INF Stopping gossipDataRoutine for peer module=consensus peer={"Data":{},"Logger":{}}
6:41AM INF Dialing peer address={"id":"e9283949d8cd716f7987c9f7c359cc49c4e97e0d","ip":"195.201.167.113","port":26656} module=p2p
6:41AM INF Stopping queryMaj23Routine for peer module=consensus peer={"Data":{},"Logger":{}}
6:41AM INF Error reconnecting to peer. Trying again addr={"id":"e9283949d8cd716f7987c9f7c359cc49c4e97e0d","ip":"195.201.167.113","port":26656} err="auth failure: secret conn failed: read tcp 172.17.0.2:53400->195.201.167.113:26656: i/o timeout" module=p2p tries=2
6:41AM INF Dialing peer address={"id":"e9283949d8cd716f7987c9f7c359cc49c4e97e0d","ip":"195.201.167.113","port":26656} module=p2p
6:41AM INF Error reconnecting to peer. Trying again addr={"id":"e9283949d8cd716f7987c9f7c359cc49c4e97e0d","ip":"195.201.167.113","port":26656} err="auth failure: secret conn failed: read tcp 172.17.0.2:53402->195.201.167.113:26656: i/o timeout" module=p2p tries=3
6:41AM INF Dialing peer address={"id":"e9283949d8cd716f7987c9f7c359cc49c4e97e0d","ip":"195.201.167.113","port":26656} module=p2p
6:41AM INF Error reconnecting to peer. Trying again addr={"id":"e9283949d8cd716f7987c9f7c359cc49c4e97e0d","ip":"195.201.167.113","port":26656} err="auth failure: secret conn failed: read tcp 172.17.0.2:53404->195.201.167.113:26656: i/o timeout" module=p2p tries=4
6:41AM INF Dialing peer address={"id":"e9283949d8cd716f7987c9f7c359cc49c4e97e0d","ip":"195.201.167.113","port":26656} module=p2p
6:41AM INF Ensure peers module=pex numDialing=1 numInPeers=0 numOutPeers=1 numToDial=8
6:41AM INF Will dial address addr={"id":"7b9839cd3e994c44cbd747d1ddc51ee695f60e58","ip":"157.90.134.48","port":26656} module=pex
6:41AM INF Will dial address addr={"id":"05bf6e5ad85ba4e91ad2b54f71178ad699902620","ip":"52.55.216.238","port":26656} module=pex
6:41AM INF Will dial address addr={"id":"2abbaa9e4d236b4bac79fa19019cd99ab1794f7d","ip":"13.212.125.236","port":26656} module=pex
6:41AM INF Will dial address addr={"id":"a5f453a75995a55d93a69fd64bbf0fe00ffb79b1","ip":"165.22.226.17","port":26656} module=pex
6:41AM INF Will dial address addr={"id":"2ad7b01a76b568703410cffa7cb53c5a8b3a7080","ip":"209.126.84.180","port":26656} module=pex
6:41AM INF Will dial address addr={"id":"7897c404b254e501fb3baf84dee36fc6265c657a","ip":"52.60.52.207","port":23622} module=pex
6:41AM INF Will dial address addr={"id":"d4ff6ea6546aecd8cac0df76e4dd3838f3ab2d9f","ip":"15.207.18.221","port":26656} module=pex
6:41AM INF Will dial address addr={"id":"38c5e77a0228027ce3956a22ae353f7401351163","ip":"217.69.3.109","port":26656} module=pex
6:41AM INF We need more addresses. Sending pexRequest to random peer module=pex peer={"Data":{},"Logger":{}}
6:41AM INF Dialing peer address={"id":"a5f453a75995a55d93a69fd64bbf0fe00ffb79b1","ip":"165.22.226.17","port":26656} module=p2p
6:41AM INF Dialing peer address={"id":"38c5e77a0228027ce3956a22ae353f7401351163","ip":"217.69.3.109","port":26656} module=p2p
6:41AM INF Dialing peer address={"id":"d4ff6ea6546aecd8cac0df76e4dd3838f3ab2d9f","ip":"15.207.18.221","port":26656} module=p2p
6:41AM INF Dialing peer address={"id":"7b9839cd3e994c44cbd747d1ddc51ee695f60e58","ip":"157.90.134.48","port":26656} module=p2p
6:41AM INF Dialing peer address={"id":"2abbaa9e4d236b4bac79fa19019cd99ab1794f7d","ip":"13.212.125.236","port":26656} module=p2p
6:41AM INF Dialing peer address={"id":"2ad7b01a76b568703410cffa7cb53c5a8b3a7080","ip":"209.126.84.180","port":26656} module=p2p
6:41AM INF Dialing peer address={"id":"05bf6e5ad85ba4e91ad2b54f71178ad699902620","ip":"52.55.216.238","port":26656} module=p2p
6:41AM INF Dialing peer address={"id":"7897c404b254e501fb3baf84dee36fc6265c657a","ip":"52.60.52.207","port":23622} module=p2p
6:41AM INF Error reconnecting to peer. Trying again addr={"id":"e9283949d8cd716f7987c9f7c359cc49c4e97e0d","ip":"195.201.167.113","port":26656} err="auth failure: secret conn failed: read tcp 172.17.0.2:53406->195.201.167.113:26656: i/o timeout" module=p2p tries=5
6:41AM ERR dialing failed (attempts: 1): dial tcp 52.60.52.207:23622: i/o timeout addr={"id":"7897c404b254e501fb3baf84dee36fc6265c657a","ip":"52.60.52.207","port":23622} module=pex
6:41AM ERR dialing failed (attempts: 1): dial tcp 52.55.216.238:26656: i/o timeout addr={"id":"05bf6e5ad85ba4e91ad2b54f71178ad699902620","ip":"52.55.216.238","port":26656} module=pex
6:41AM ERR dialing failed (attempts: 1): dial tcp 165.22.226.17:26656: i/o timeout addr={"id":"a5f453a75995a55d93a69fd64bbf0fe00ffb79b1","ip":"165.22.226.17","port":26656} module=pex
6:41AM ERR dialing failed (attempts: 1): dial tcp 13.212.125.236:26656: i/o timeout addr={"id":"2abbaa9e4d236b4bac79fa19019cd99ab1794f7d","ip":"13.212.125.236","port":26656} module=pex
6:41AM ERR dialing failed (attempts: 1): auth failure: secret conn failed: read tcp 172.17.0.2:34674->15.207.18.221:26656: i/o timeout addr={"id":"d4ff6ea6546aecd8cac0df76e4dd3838f3ab2d9f","ip":"15.207.18.221","port":26656} module=pex
6:41AM ERR dialing failed (attempts: 1): auth failure: secret conn failed: read tcp 172.17.0.2:37246->157.90.134.48:26656: i/o timeout addr={"id":"7b9839cd3e994c44cbd747d1ddc51ee695f60e58","ip":"157.90.134.48","port":26656} module=pex
6:41AM ERR dialing failed (attempts: 1): auth failure: secret conn failed: read tcp 172.17.0.2:54396->209.126.84.180:26656: i/o timeout addr={"id":"2ad7b01a76b568703410cffa7cb53c5a8b3a7080","ip":"209.126.84.180","port":26656} module=pex
6:41AM ERR dialing failed (attempts: 1): auth failure: secret conn failed: read tcp 172.17.0.2:34906->217.69.3.109:26656: i/o timeout addr={"id":"38c5e77a0228027ce3956a22ae353f7401351163","ip":"217.69.3.109","port":26656} module=pex
6:41AM INF minted coins from module account amount=5545415uxprt from=mint module=x/bank
6:41AM INF executed block height=1 module=state num_invalid_txs=0 num_valid_txs=0
6:41AM INF commit synced commit=436F6D6D697449447B5B313739203230312033352031352034332039392038342031373520313533203332203135352031313620313536203139352031373920373920313438203231312031373420383520323530203137382034372032362032353420323338203734203131203232203232332039342036355D3A317D
6:41AM INF committed state app_hash=B3C9230F2B6354AF99209B749CC3B34F94D3AE55FAB22F1AFEEE4A0B16DF5E41 height=1 module=state num_txs=0
6:41AM INF indexed block height=1 module=txindex
6:41AM INF Dialing peer address={"id":"e9283949d8cd716f7987c9f7c359cc49c4e97e0d","ip":"195.201.167.113","port":26656} module=p2p
6:41AM INF Error reconnecting to peer. Trying again addr={"id":"e9283949d8cd716f7987c9f7c359cc49c4e97e0d","ip":"195.201.167.113","port":26656} err="auth failure: secret conn failed: read tcp 172.17.0.2:53408->195.201.167.113:26656: i/o timeout" module=p2p tries=6
6:42AM INF Dialing peer address={"id":"e9283949d8cd716f7987c9f7c359cc49c4e97e0d","ip":"195.201.167.113","port":26656} module=p2p
panic: Failed to process committed block (2:235D60A303BCC8185ACD1DB8C163F6DA422C0F1ACFD87D84D78A005268F1CCD9): wrong Block.Header.AppHash.  Expected B3C9230F2B6354AF99209B749CC3B34F94D3AE55FAB22F1AFEEE4A0B16DF5E41, got D6D5FB195D230E170C3B147EB48FA8D248D8CEB53772DF8994244F82669126F0

goroutine 114 [running]:
github.com/tendermint/tendermint/blockchain/v0.(*BlockchainReactor).poolRoutine(0xc002c64000, 0x0)
	/go/pkg/mod/github.com/tendermint/tendermint@v0.34.14/blockchain/v0/reactor.go:401 +0x123a
created by github.com/tendermint/tendermint/blockchain/v0.(*BlockchainReactor).OnStart
	/go/pkg/mod/github.com/tendermint/tendermint@v0.34.14/blockchain/v0/reactor.go:110 +0x7a
```
